// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAekQTapmJ-utVcqUyfAgBZ6-OJHmA3OpA',
    appId: '1:519634335659:web:def6d0e466cfd9da2544ee',
    messagingSenderId: '519634335659',
    projectId: 'myfirstdb-7a365',
    authDomain: 'myfirstdb-7a365.firebaseapp.com',
    storageBucket: 'myfirstdb-7a365.firebasestorage.app',
    measurementId: 'G-S7LETZCNJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vibOWA2qPZdDTGnFsCr02z8EzHn3Nq8',
    appId: '1:519634335659:android:7f8d58ad43df8d042544ee',
    messagingSenderId: '519634335659',
    projectId: 'myfirstdb-7a365',
    storageBucket: 'myfirstdb-7a365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYJzuLpFKzXnMuTwxY0coFejo-9_3Ssw',
    appId: '1:519634335659:ios:6d26cb3aa26c0b412544ee',
    messagingSenderId: '519634335659',
    projectId: 'myfirstdb-7a365',
    storageBucket: 'myfirstdb-7a365.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );
}
