// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADJxI9E7UyZCZYToUCa5Lcuzx7aBveG5k',
    appId: '1:51128747627:web:7f9d701a97d69e07d2132e',
    messagingSenderId: '51128747627',
    projectId: 'db2211b1',
    authDomain: 'db2211b1.firebaseapp.com',
    storageBucket: 'db2211b1.firebasestorage.app',
    measurementId: 'G-HK19W7Y2WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACer5Um8vBck-DSWbBiTLlrmZ9oxWFJCc',
    appId: '1:51128747627:android:4a52bfd2794a0881d2132e',
    messagingSenderId: '51128747627',
    projectId: 'db2211b1',
    storageBucket: 'db2211b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8wRoTirIcnIrFGLsOabgfnEe_9OsLKM',
    appId: '1:51128747627:ios:c0af9858fe19a8c2d2132e',
    messagingSenderId: '51128747627',
    projectId: 'db2211b1',
    storageBucket: 'db2211b1.firebasestorage.app',
    iosBundleId: 'com.example.myfirebaseapp',
  );
}
